services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id','runreal/runreal']
    volumes:
      - ".:/plugin:ro"
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"