name: runreal
description: Download runreal and makes available to environment
author: https://github.com/runreal
requirements: []
configuration:
  properties:
    version:
      type: string
      default: latest
    from_source:
      type: boolean
      default: false
    from_ref:
      type: string
  additionalProperties: true